# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .input_types import RunsFilter
from .runs_for_ingestion import RunsForIngestion


def gql(q: str) -> str:
    return q


class DagsterGraphQLClient(AsyncBaseClient):
    async def runs_for_ingestion(
        self,
        filter_: Union[Optional[RunsFilter], UnsetType] = UNSET,
        cursor: Union[Optional[str], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> RunsForIngestion:
        query = gql("""
            query RunsForIngestion($filter: RunsFilter, $cursor: String, $limit: Int) {
              runsOrError(filter: $filter, cursor: $cursor, limit: $limit) {
                __typename
                ... on Runs {
                  results {
                    runId
                    jobName
                    status
                    creationTime
                    updateTime
                    startTime
                    endTime
                    parentRunId
                    rootRunId
                    assetSelection {
                      path
                    }
                    tags {
                      key
                      value
                    }
                  }
                }
                ... on PythonError {
                  message
                  stack
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "cursor": cursor,
            "limit": limit,
        }
        response = await self.execute(
            query=query,
            operation_name="RunsForIngestion",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return RunsForIngestion.model_validate(data)
