# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class LegacySkipEventDetails(BaseModel):
    run_id: str = Field(alias="runId")
    step_key: Optional[str] = Field(alias="stepKey")
    timestamp: str
    message: str


class MaterializationEventDetails(BaseModel):
    run_id: str = Field(alias="runId")
    step_key: Optional[str] = Field(alias="stepKey")
    timestamp: str
    partition: Optional[str]
    asset_key: Optional["MaterializationEventDetailsAssetKey"] = Field(alias="assetKey")
    metadata_entries: list[
        Annotated[
            Union[
                "MaterializationEventDetailsMetadataEntriesMetadataEntry",
                "MaterializationEventDetailsMetadataEntriesTextMetadataEntry",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="metadataEntries")


class MaterializationEventDetailsAssetKey(BaseModel):
    path: list[str]


class MaterializationEventDetailsMetadataEntriesMetadataEntry(BaseModel):
    typename__: Literal[
        "AssetMetadataEntry",
        "BoolMetadataEntry",
        "CodeReferencesMetadataEntry",
        "FloatMetadataEntry",
        "IntMetadataEntry",
        "JobMetadataEntry",
        "JsonMetadataEntry",
        "MarkdownMetadataEntry",
        "MetadataEntry",
        "NotebookMetadataEntry",
        "NullMetadataEntry",
        "PathMetadataEntry",
        "PipelineRunMetadataEntry",
        "PoolMetadataEntry",
        "PythonArtifactMetadataEntry",
        "TableColumnLineageMetadataEntry",
        "TableMetadataEntry",
        "TableSchemaMetadataEntry",
        "TimestampMetadataEntry",
        "UrlMetadataEntry",
    ] = Field(alias="__typename")
    label: str


class MaterializationEventDetailsMetadataEntriesTextMetadataEntry(BaseModel):
    typename__: Literal["TextMetadataEntry"] = Field(alias="__typename")
    label: str
    text: str


class ObservationEventDetails(BaseModel):
    run_id: str = Field(alias="runId")
    step_key: Optional[str] = Field(alias="stepKey")
    timestamp: str
    partition: Optional[str]
    asset_key: Optional["ObservationEventDetailsAssetKey"] = Field(alias="assetKey")
    metadata_entries: list[
        Annotated[
            Union[
                "ObservationEventDetailsMetadataEntriesMetadataEntry",
                "ObservationEventDetailsMetadataEntriesTextMetadataEntry",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="metadataEntries")


class ObservationEventDetailsAssetKey(BaseModel):
    path: list[str]


class ObservationEventDetailsMetadataEntriesMetadataEntry(BaseModel):
    typename__: Literal[
        "AssetMetadataEntry",
        "BoolMetadataEntry",
        "CodeReferencesMetadataEntry",
        "FloatMetadataEntry",
        "IntMetadataEntry",
        "JobMetadataEntry",
        "JsonMetadataEntry",
        "MarkdownMetadataEntry",
        "MetadataEntry",
        "NotebookMetadataEntry",
        "NullMetadataEntry",
        "PathMetadataEntry",
        "PipelineRunMetadataEntry",
        "PoolMetadataEntry",
        "PythonArtifactMetadataEntry",
        "TableColumnLineageMetadataEntry",
        "TableMetadataEntry",
        "TableSchemaMetadataEntry",
        "TimestampMetadataEntry",
        "UrlMetadataEntry",
    ] = Field(alias="__typename")
    label: str


class ObservationEventDetailsMetadataEntriesTextMetadataEntry(BaseModel):
    typename__: Literal["TextMetadataEntry"] = Field(alias="__typename")
    label: str
    text: str


class PlannedMaterializationEventDetails(BaseModel):
    run_id: str = Field(alias="runId")
    step_key: Optional[str] = Field(alias="stepKey")
    timestamp: str
    asset_key: Optional["PlannedMaterializationEventDetailsAssetKey"] = Field(
        alias="assetKey"
    )


class PlannedMaterializationEventDetailsAssetKey(BaseModel):
    path: list[str]


LegacySkipEventDetails.model_rebuild()
MaterializationEventDetails.model_rebuild()
ObservationEventDetails.model_rebuild()
PlannedMaterializationEventDetails.model_rebuild()
