# Generated by ariadne-codegen
# Source: https://processing.imap-mission.com/graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import RunStatus


class ExecutionTag(BaseModel):
    key: str
    value: str


class RunsFilter(BaseModel):
    run_ids: Optional[list[Optional[str]]] = Field(alias="runIds", default=None)
    pipeline_name: Optional[str] = Field(alias="pipelineName", default=None)
    tags: Optional[list["ExecutionTag"]] = None
    statuses: Optional[list[RunStatus]] = None
    snapshot_id: Optional[str] = Field(alias="snapshotId", default=None)
    updated_after: Optional[float] = Field(alias="updatedAfter", default=None)
    updated_before: Optional[float] = Field(alias="updatedBefore", default=None)
    created_before: Optional[float] = Field(alias="createdBefore", default=None)
    created_after: Optional[float] = Field(alias="createdAfter", default=None)
    mode: Optional[str] = None


RunsFilter.model_rebuild()
