# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Annotated, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import (
    LegacySkipEventDetails,
    MaterializationEventDetails,
    ObservationEventDetails,
    PlannedMaterializationEventDetails,
)


class RunDetails(BaseModel):
    runs_or_error: Union[
        "RunDetailsRunsOrErrorRuns",
        "RunDetailsRunsOrErrorInvalidPipelineRunsFilterError",
        "RunDetailsRunsOrErrorPythonError",
    ] = Field(alias="runsOrError", discriminator="typename__")


class RunDetailsRunsOrErrorRuns(BaseModel):
    typename__: Literal["Runs"] = Field(alias="__typename")
    results: list["RunDetailsRunsOrErrorRunsResults"]


class RunDetailsRunsOrErrorRunsResults(BaseModel):
    run_id: str = Field(alias="runId")
    event_connection: "RunDetailsRunsOrErrorRunsResultsEventConnection" = Field(
        alias="eventConnection"
    )


class RunDetailsRunsOrErrorRunsResultsEventConnection(BaseModel):
    events: list[
        Annotated[
            Union[
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepFailureEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepInputEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepOutputEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepSkippedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepStartEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepSuccessEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepUpForRetryEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepRestartEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHealthChangedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLogMessageEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitFailureEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitStartedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitSuccessEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunFailureEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunStartEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunEnqueuedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunDequeuedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunStartingEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunCancelingEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunCanceledEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunSuccessEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepWorkerStartedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepWorkerStartingEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHandledOutputEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLoadedInputEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLogsCapturedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsObjectStoreOperationEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepExpectationResultEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsMaterializationEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsObservationEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsFailedToMaterializeEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsEngineEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookCompletedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookSkippedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookErroredEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertStartEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertSuccessEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertFailureEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetMaterializationPlannedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetCheckEvaluationPlannedEvent",
                "RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetCheckEvaluationEvent",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    cursor: str
    has_more: bool = Field(alias="hasMore")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepFailureEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepFailureEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepInputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepInputEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepOutputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepOutputEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepSkippedEvent(
    LegacySkipEventDetails
):
    typename__: Literal["ExecutionStepSkippedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepStartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepStartEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepSuccessEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepSuccessEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepUpForRetryEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepUpForRetryEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsExecutionStepRestartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepRestartEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHealthChangedEvent(
    BaseModel
):
    typename__: Literal["HealthChangedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLogMessageEvent(BaseModel):
    typename__: Literal["LogMessageEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitFailureEvent(
    BaseModel
):
    typename__: Literal["ResourceInitFailureEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitStartedEvent(
    BaseModel
):
    typename__: Literal["ResourceInitStartedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsResourceInitSuccessEvent(
    BaseModel
):
    typename__: Literal["ResourceInitSuccessEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunFailureEvent(BaseModel):
    typename__: Literal["RunFailureEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunStartEvent(BaseModel):
    typename__: Literal["RunStartEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunEnqueuedEvent(BaseModel):
    typename__: Literal["RunEnqueuedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunDequeuedEvent(BaseModel):
    typename__: Literal["RunDequeuedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunStartingEvent(BaseModel):
    typename__: Literal["RunStartingEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunCancelingEvent(BaseModel):
    typename__: Literal["RunCancelingEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunCanceledEvent(BaseModel):
    typename__: Literal["RunCanceledEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsRunSuccessEvent(BaseModel):
    typename__: Literal["RunSuccessEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepWorkerStartedEvent(
    BaseModel
):
    typename__: Literal["StepWorkerStartedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepWorkerStartingEvent(
    BaseModel
):
    typename__: Literal["StepWorkerStartingEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHandledOutputEvent(
    BaseModel
):
    typename__: Literal["HandledOutputEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLoadedInputEvent(BaseModel):
    typename__: Literal["LoadedInputEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsLogsCapturedEvent(BaseModel):
    typename__: Literal["LogsCapturedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsObjectStoreOperationEvent(
    BaseModel
):
    typename__: Literal["ObjectStoreOperationEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsStepExpectationResultEvent(
    BaseModel
):
    typename__: Literal["StepExpectationResultEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsMaterializationEvent(
    MaterializationEventDetails
):
    typename__: Literal["MaterializationEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsObservationEvent(
    ObservationEventDetails
):
    typename__: Literal["ObservationEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsFailedToMaterializeEvent(
    BaseModel
):
    typename__: Literal["FailedToMaterializeEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsEngineEvent(BaseModel):
    typename__: Literal["EngineEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookCompletedEvent(
    BaseModel
):
    typename__: Literal["HookCompletedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookSkippedEvent(BaseModel):
    typename__: Literal["HookSkippedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsHookErroredEvent(BaseModel):
    typename__: Literal["HookErroredEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertStartEvent(BaseModel):
    typename__: Literal["AlertStartEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertSuccessEvent(BaseModel):
    typename__: Literal["AlertSuccessEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAlertFailureEvent(BaseModel):
    typename__: Literal["AlertFailureEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetMaterializationPlannedEvent(
    PlannedMaterializationEventDetails
):
    typename__: Literal["AssetMaterializationPlannedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetCheckEvaluationPlannedEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationPlannedEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorRunsResultsEventConnectionEventsAssetCheckEvaluationEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationEvent"] = Field(alias="__typename")


class RunDetailsRunsOrErrorInvalidPipelineRunsFilterError(BaseModel):
    typename__: Literal["InvalidPipelineRunsFilterError"] = Field(alias="__typename")
    message: str


class RunDetailsRunsOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


RunDetails.model_rebuild()
RunDetailsRunsOrErrorRuns.model_rebuild()
RunDetailsRunsOrErrorRunsResults.model_rebuild()
RunDetailsRunsOrErrorRunsResultsEventConnection.model_rebuild()
