# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel


class RunCount(BaseModel):
    runs_or_error: Union[
        "RunCountRunsOrErrorRuns",
        "RunCountRunsOrErrorInvalidPipelineRunsFilterError",
        "RunCountRunsOrErrorPythonError",
    ] = Field(alias="runsOrError", discriminator="typename__")


class RunCountRunsOrErrorRuns(BaseModel):
    typename__: Literal["Runs"] = Field(alias="__typename")
    count: int


class RunCountRunsOrErrorInvalidPipelineRunsFilterError(BaseModel):
    typename__: Literal["InvalidPipelineRunsFilterError"] = Field(alias="__typename")


class RunCountRunsOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


RunCount.model_rebuild()
