# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Annotated, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import (
    LegacySkipEventDetails,
    MaterializationEventDetails,
    ObservationEventDetails,
    PlannedMaterializationEventDetails,
)


class RunDetailsPage(BaseModel):
    run_or_error: Union[
        "RunDetailsPageRunOrErrorRun",
        "RunDetailsPageRunOrErrorRunNotFoundError",
        "RunDetailsPageRunOrErrorPythonError",
    ] = Field(alias="runOrError", discriminator="typename__")


class RunDetailsPageRunOrErrorRun(BaseModel):
    typename__: Literal["Run"] = Field(alias="__typename")
    event_connection: "RunDetailsPageRunOrErrorRunEventConnection" = Field(
        alias="eventConnection"
    )


class RunDetailsPageRunOrErrorRunEventConnection(BaseModel):
    events: list[
        Annotated[
            Union[
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepFailureEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepInputEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepOutputEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepSkippedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepStartEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepSuccessEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepUpForRetryEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepRestartEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsHealthChangedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsLogMessageEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitFailureEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitStartedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitSuccessEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunFailureEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunStartEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunEnqueuedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunDequeuedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunStartingEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunCancelingEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunCanceledEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsRunSuccessEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsStepWorkerStartedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsStepWorkerStartingEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsHandledOutputEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsLoadedInputEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsLogsCapturedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsObjectStoreOperationEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsStepExpectationResultEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsMaterializationEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsObservationEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsFailedToMaterializeEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsEngineEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsHookCompletedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsHookSkippedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsHookErroredEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAlertStartEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAlertSuccessEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAlertFailureEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAssetMaterializationPlannedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAssetCheckEvaluationPlannedEvent",
                "RunDetailsPageRunOrErrorRunEventConnectionEventsAssetCheckEvaluationEvent",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    cursor: str
    has_more: bool = Field(alias="hasMore")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepFailureEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepFailureEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepInputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepInputEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepOutputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepOutputEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepSkippedEvent(
    LegacySkipEventDetails
):
    typename__: Literal["ExecutionStepSkippedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepStartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepStartEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepSuccessEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepSuccessEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepUpForRetryEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepUpForRetryEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsExecutionStepRestartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepRestartEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsHealthChangedEvent(BaseModel):
    typename__: Literal["HealthChangedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsLogMessageEvent(BaseModel):
    typename__: Literal["LogMessageEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitFailureEvent(
    BaseModel
):
    typename__: Literal["ResourceInitFailureEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitStartedEvent(
    BaseModel
):
    typename__: Literal["ResourceInitStartedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsResourceInitSuccessEvent(
    BaseModel
):
    typename__: Literal["ResourceInitSuccessEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunFailureEvent(BaseModel):
    typename__: Literal["RunFailureEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunStartEvent(BaseModel):
    typename__: Literal["RunStartEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunEnqueuedEvent(BaseModel):
    typename__: Literal["RunEnqueuedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunDequeuedEvent(BaseModel):
    typename__: Literal["RunDequeuedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunStartingEvent(BaseModel):
    typename__: Literal["RunStartingEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunCancelingEvent(BaseModel):
    typename__: Literal["RunCancelingEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunCanceledEvent(BaseModel):
    typename__: Literal["RunCanceledEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsRunSuccessEvent(BaseModel):
    typename__: Literal["RunSuccessEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsStepWorkerStartedEvent(BaseModel):
    typename__: Literal["StepWorkerStartedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsStepWorkerStartingEvent(
    BaseModel
):
    typename__: Literal["StepWorkerStartingEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsHandledOutputEvent(BaseModel):
    typename__: Literal["HandledOutputEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsLoadedInputEvent(BaseModel):
    typename__: Literal["LoadedInputEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsLogsCapturedEvent(BaseModel):
    typename__: Literal["LogsCapturedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsObjectStoreOperationEvent(
    BaseModel
):
    typename__: Literal["ObjectStoreOperationEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsStepExpectationResultEvent(
    BaseModel
):
    typename__: Literal["StepExpectationResultEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsMaterializationEvent(
    MaterializationEventDetails
):
    typename__: Literal["MaterializationEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsObservationEvent(
    ObservationEventDetails
):
    typename__: Literal["ObservationEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsFailedToMaterializeEvent(
    BaseModel
):
    typename__: Literal["FailedToMaterializeEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsEngineEvent(BaseModel):
    typename__: Literal["EngineEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsHookCompletedEvent(BaseModel):
    typename__: Literal["HookCompletedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsHookSkippedEvent(BaseModel):
    typename__: Literal["HookSkippedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsHookErroredEvent(BaseModel):
    typename__: Literal["HookErroredEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAlertStartEvent(BaseModel):
    typename__: Literal["AlertStartEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAlertSuccessEvent(BaseModel):
    typename__: Literal["AlertSuccessEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAlertFailureEvent(BaseModel):
    typename__: Literal["AlertFailureEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAssetMaterializationPlannedEvent(
    PlannedMaterializationEventDetails
):
    typename__: Literal["AssetMaterializationPlannedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAssetCheckEvaluationPlannedEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationPlannedEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunEventConnectionEventsAssetCheckEvaluationEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationEvent"] = Field(alias="__typename")


class RunDetailsPageRunOrErrorRunNotFoundError(BaseModel):
    typename__: Literal["RunNotFoundError"] = Field(alias="__typename")
    message: str


class RunDetailsPageRunOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


RunDetailsPage.model_rebuild()
RunDetailsPageRunOrErrorRun.model_rebuild()
RunDetailsPageRunOrErrorRunEventConnection.model_rebuild()
