# Generated by ariadne-codegen
# Source: sds_utils/dashboard/backend/query/graphql

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import RunStatus


class RunsForIngestion(BaseModel):
    runs_or_error: Union[
        "RunsForIngestionRunsOrErrorRuns",
        "RunsForIngestionRunsOrErrorInvalidPipelineRunsFilterError",
        "RunsForIngestionRunsOrErrorPythonError",
    ] = Field(alias="runsOrError", discriminator="typename__")


class RunsForIngestionRunsOrErrorRuns(BaseModel):
    typename__: Literal["Runs"] = Field(alias="__typename")
    results: list["RunsForIngestionRunsOrErrorRunsResults"]


class RunsForIngestionRunsOrErrorRunsResults(BaseModel):
    run_id: str = Field(alias="runId")
    job_name: str = Field(alias="jobName")
    status: RunStatus
    creation_time: float = Field(alias="creationTime")
    update_time: Optional[float] = Field(alias="updateTime")
    start_time: Optional[float] = Field(alias="startTime")
    end_time: Optional[float] = Field(alias="endTime")
    parent_run_id: Optional[str] = Field(alias="parentRunId")
    root_run_id: Optional[str] = Field(alias="rootRunId")
    asset_selection: Optional[
        list["RunsForIngestionRunsOrErrorRunsResultsAssetSelection"]
    ] = Field(alias="assetSelection")
    tags: list["RunsForIngestionRunsOrErrorRunsResultsTags"]


class RunsForIngestionRunsOrErrorRunsResultsAssetSelection(BaseModel):
    path: list[str]


class RunsForIngestionRunsOrErrorRunsResultsTags(BaseModel):
    key: str
    value: str


class RunsForIngestionRunsOrErrorInvalidPipelineRunsFilterError(BaseModel):
    typename__: Literal["InvalidPipelineRunsFilterError"] = Field(alias="__typename")


class RunsForIngestionRunsOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


RunsForIngestion.model_rebuild()
RunsForIngestionRunsOrErrorRuns.model_rebuild()
RunsForIngestionRunsOrErrorRunsResults.model_rebuild()
